CN-22-Bus-stop-tooltips-do-not-update
catbus-navigator/web-ui pull request #12
Opened 2023-04-02 19:29 UTC by qmohitsingh

# Description

Please include a summary of the changes and the related issue. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # [CN-22](https://jpt4.atlassian.net/browse/CN-22)

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

# Checklist:

- [ ] Have you merged main into this branch and resolved any conflicts?
- [ ] Have you updated any necessary documentation?
- [ ] Have you successfully run tests with your changes locally?

2023-04-02 23:32 UTC, johnpturner8 requested changes
This isn't working right for me. The tooltip cycles between other bus stops, instead of showing the bus stop I clicked on. The bus stops shown seem to be any stops I have clicked during a session.

2023-04-03 01:18 UTC, qmohitsingh commented
> This isn't working right for me. The tooltip cycles between other bus stops, instead of showing the bus stop I clicked on. The bus stops shown seem to be any stops I have clicked during a session.
> 
> Also, be sure to merge with main.

Yeah, I just noticed, not sure why it's happening, let me see if I can debug it

2023-04-10 01:28 UTC, cjanse approved these changes
Everything seems to work. I tested this our using Sikes Hall - East with the Red Route. I had my.clemson pulled up along with out web-app to ensure that both of them were working together correctly

2023-04-10 01:34 UTC, cjanse approved these changes

2023-04-10 02:53 UTC, johnpturner8 approved these changes

2023-04-10 02:54 UTC, merged