Can type addresses and get their value
catbus-navigator/web-ui pull request #5
Opened 2023-02-27 00:00 UTC by cjanse

# Description

Please include a summary of the changes and the related issue. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # [CN-](https://jpt4.atlassian.net/browse/CN-)

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

# Checklist:

- [ ] Have you merged main into this branch and resolved any conflicts?
- [ ] Have you updated any necessary documentation?
- [ ] Have you successfully run tests with your changes locally?

2023-03-01 22:21 UTC, johnpturner8 requested changes
- Only the starting address has autofill
- Searching does not update the route
- Scrolling down results in the search box becoming inaccessible. You can probably just adjust the size to 90% or something like that

Also, don't forget to fill out the PR template next time :)

2023-03-04 20:55 UTC, cjanse commented
Tests Ran:

1.) Ran a test with starting address 102 Calhoun Street Clemson and ending address 101 Calhoun Drive Clemson
2.) Changed the starting address to 104 Calhoun Street Clemson and kept ending address the same
3.) Changed ending address to 105 Calhoun Drive Clemson
4.) Repeated tests 1-3 but removed Clemson from the end.

No errors were found

2023-03-05 17:50 UTC, johnpturner8 submitted a review, later dismissed

2023-03-05 17:51 UTC, johnpturner8 commented
Looks good. Pushed a quick css fix

2023-03-05 23:13 UTC, sdalley0509 approved these changes

2023-03-05 23:14 UTC, merged